apiVersion: v1
kind: Namespace
metadata:
  labels:
    cozystack.io/system: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: qosi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-apps
  namespace: qosi
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/tabu-a/external-apps-example.git
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-apps
  namespace: qosi
spec:
  interval: 1m
  targetNamespace: cozy-system
  chart:
    spec:
      chart: ./packages/core/platform
      sourceRef:
        kind: GitRepository
        name: external-apps
        namespace: qosi
      version: '*'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpt-oss-20b
  namespace: qosi
spec:
  interval: 1m
  targetNamespace: cozy-system
  chart:
    spec:
      chart: ./packages/apps/gpt-oss-20b
      sourceRef:
        kind: GitRepository
        name: external-apps
        namespace: qosi
      version: '*'
