apiVersion: v1
kind: Namespace
metadata:
  labels:
    cozystack.io/system: "true"
  name: qosi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuberay
  namespace: qosi
spec:
  interval: 1m0s
  url: https://ray-project.github.io/kuberay-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: qosi
spec:
  chart:
    spec:
      chart: kuberay-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kuberay
      version: 1.1.0
  interval: 1m0s
